# Generated by Django 4.0.2 on 2022-03-14 19:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=30, verbose_name='Subtitulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', ckeditor.fields.RichTextField()),
                ('fecha_creacion_mensaje', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('autor_mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dirigido_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppViajes.post')),
            ],
        ),
    ]
