# Generated by Django 4.0.2 on 2022-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('contenido', models.TextField(max_length=100)),
                ('fecha', models.DateField()),
                ('deNombre', models.CharField(max_length=30)),
                ('deEmail', models.EmailField(max_length=254)),
                ('paraNombre', models.CharField(max_length=30)),
                ('paraEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('alta', models.DateField()),
            ],
        ),
    ]
