# Generated by Django 4.0.3 on 2022-03-07 18:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppViajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=30, verbose_name='Subtitulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('imagen', models.ImageField(upload_to='imagenes_post/', verbose_name='Imagen Referencial')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='deEmail',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='deNombre',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='paraEmail',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='paraNombre',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='titulo',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='autor_mensaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='fecha_creacion_mensaje',
            field=models.DateField(auto_now_add=True, default=1, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(default=1, max_length=100, verbose_name='Mensaje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='dirigido_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppViajes.post'),
            preserve_default=False,
        ),
    ]
