# Generated by Django 4.0.2 on 2022-03-04 12:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0002_post_delete_blog_delete_mensaje_remove_usuario_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', ckeditor.fields.RichTextField()),
                ('fecha_creacion_mensaje', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('autor_mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppViajes.usuario')),
            ],
        ),
    ]
