# Generated by Django 4.0.2 on 2022-03-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0002_post_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
