# Generated by Django 4.0.2 on 2022-03-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0003_post_subtitulo_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='mensaje',
        ),
    ]
