# Generated by Django 4.0.2 on 2022-03-08 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppViajes', '0004_remove_mensaje_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='dirigido_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppViajes.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(default=1, max_length=100, verbose_name='Mensaje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='autor_mensaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(max_length=30, verbose_name='Subtitulo'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
