# Generated by Django 4.0.2 on 2022-03-13 14:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0005_mensaje_dirigido_a_mensaje_mensaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
