# Generated by Django 4.0.2 on 2022-03-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0007_post_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
