# Generated by Django 4.0.3 on 2022-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
        migrations.AddField(
            model_name='profile',
            name='descripcion',
            field=models.CharField(default=1, max_length=120, verbose_name='Subtitulo'),
            preserve_default=False,
        ),
    ]
