# Generated by Django 4.0.3 on 2022-03-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0003_profile_foto_profile_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='descripcion',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Descripción'),
        ),
    ]
