# Generated by Django 4.0.3 on 2022-03-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0004_profile_apellido_profile_email_profile_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombre',
        ),
    ]
