# Generated by Django 4.0.3 on 2022-03-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0005_remove_profile_apellido_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre'),
        ),
    ]
