# Generated by Django 4.0.3 on 2022-03-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0007_alter_profile_apellido_alter_profile_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='descripcion',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
